######################################################################
##
## Filename: tb_noekeon.udo
## Created on: Mon Mar 02 9:32:53 GMT Standard Time 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
add wave -position insertpoint  \
sim:/tb_noekeon/uut/ROUND_F_0/a_0_out \
sim:/tb_noekeon/uut/ROUND_F_0/a_1_out \
sim:/tb_noekeon/uut/ROUND_F_0/a_2_out \
sim:/tb_noekeon/uut/ROUND_F_0/a_3_out
add wave -position insertpoint  \
sim:/tb_noekeon/uut/ROUND_F_0/a_0_in \
sim:/tb_noekeon/uut/ROUND_F_0/a_1_in \
sim:/tb_noekeon/uut/ROUND_F_0/a_2_in \
sim:/tb_noekeon/uut/ROUND_F_0/a_3_in
add wave -position insertpoint  \
sim:/tb_noekeon/uut/ROUND_F_0/rc_in